### ISSUE TITLE
JSC API not listed

### ISSUE THREAD

**Issue by ryaninvents** [ptomato/devdocs#11]
_(Note: It looks like the Trello board is for the main DevDocs at `devdocs.io`, so I disregarded the instructions in the issue template. Let me know if this was an incorrect assumption.)_

I'm looking for information on the JavaScriptCore API; specifically, how to unmarshal values returned by the [WebKit2.UserContentManager.script-message-received](https://devdocs.baznga.org/webkit240~4.0_api/webkit2.usercontentmanager#signal-script-message-received) signal. It seems that it's been implemented, but not yet pushed to DevDocs.

- [Relevant conversation](https://gitlab.gnome.org/GNOME/gjs/issues/7#note_315279)
- [C API](https://webkitgtk.org/reference/jsc-glib/stable/index.html)

**Comment by ptomato** [comment]
Does anyone know what package to install on Fedora 29 to get the GIR file for this API?
