### ISSUE TITLE
GLib.KeyFile documentation missing

### ISSUE THREAD

**Issue by sonnyp** [ptomato/devdocs#14]
https://gjs-docs.gnome.org/glib20~2.60.1/glib.keyfile 404
however https://gjs-docs.gnome.org/glib20~2.60.1/glib.keyfileerror is :ok_hand:

**Comment by sonnyp** [comment]
GstWebRTC too

**Comment by ptomato** [comment]
Moved to https://gitlab.gnome.org/GNOME/devdocsgjs/-/issues/15 and https://gitlab.gnome.org/GNOME/devdocsgjs/-/issues/16
