### ISSUE TITLE
Mutter documentation

### ISSUE THREAD

**Issue by olejorgenb** [ptomato/devdocs#4]
https://developer.gnome.org/meta/stable/

Quite crucial when developing certain types of gnome shell extensions.

(https://developer.gnome.org/st/stable/ would be nice too)

PS: Assuming the  https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md doesn't apply to this fork

**Comment by 3v1n0** [comment]
Yeah, I agree this is something to be added please :)

For extension development, even St and other Shell girs could be useful

**Comment by olejorgenb** [comment]
I later found out that the mutter documentation is very out of date and no longer updated: :( https://gitlab.gnome.org/GNOME/mutter/commit/7dc0b0e6022ef101aac4987aee8363c0330d58f1

**Comment by ptomato** [comment]
Luckily, we don't need that gtk-doc documentation, we generate it from the GIR file. The difficult part of this issue will be ensuring the Mutter-1.0.gir and St-1.0.gir on the Docker container when generating the image, as they are usually linked directly into gnome-shell if I'm not mistaken?

**Comment by 3v1n0** [comment]
That's true for St, but Mutter should not.

**Comment by ptomato** [comment]
Huh, it was the exact opposite of what I thought. The gnome-shell package in Fedora 29 will install Gvc-1.0.gir, Shell-0.1.gir, ShellMenu-0.1.gir, and St-1.0.gir in `/usr/share/gnome-shell`, so with a small adjustment to the scraper to handle the nonstandard location it should be possible to add these.

I can't find out where Mutter-1.0.gir lives, or what package to install to get it, though.

**Comment by 3v1n0** [comment]
In Ubuntu they're just inside the mutter libfolder:

```bash
$ ls /usr/lib/x86_64-linux-gnu/mutter-4/*.gir -1
/usr/lib/x86_64-linux-gnu/mutter-4/Cally-4.gir
/usr/lib/x86_64-linux-gnu/mutter-4/Clutter-4.gir
/usr/lib/x86_64-linux-gnu/mutter-4/ClutterX11-4.gir
/usr/lib/x86_64-linux-gnu/mutter-4/Cogl-4.gir
/usr/lib/x86_64-linux-gnu/mutter-4/CoglPango-4.gir
/usr/lib/x86_64-linux-gnu/mutter-4/Meta-4.gir
```

So it's `Meta-*.gir` not `Mutter-*.gir` ;-).
And probably even mutter-Clutter and friends should take part to the fun

**Comment by ptomato** [comment]
Hmm, the Fedora `mutter-devel` package doesn't install any GIR file at all, or at least that's what I thought when I checked yesterday evening. I'll check again next time I continue working on this server.

**Comment by ptomato** [comment]
Found it, it's in the `mutter` package directly instead of `mutter-devel`.

**Comment by ptomato** [comment]
This should be fixed whenever the new image is able to be deployed.
